import type { Project, Roadmap } from '@/types';

export type ExportableProject = {
  id: string;
  title: string;
  description?: string | null;
  status: string;
  progress: number;
  createdAt: string;
  updatedAt: string;
  technologies: string[];
  tags: string[];
  milestones: Array<{
    title: string;
    description?: string;
    duration?: string;
    completed: boolean;
    tasks: string[];
  }>;
  relatedLinks: Array<{ label: string; url: string }>;
};

const normalizeText = (value?: string | null) => value?.trim() || 'Not provided';

export function sanitizeFileName(title: string): string {
  const sanitized = title
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z0-9-_ ]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .toLowerCase();

  return sanitized || 'project-summary';
}

function escapeMarkdown(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/([`*_{}\[\]()#+.!|>-])/g, '\\$1');
}

function formatDate(value: string): string {
  const date = new Date(value);
  return Number.isNaN(date.getTime())
    ? 'Not available'
    : new Intl.DateTimeFormat('en', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      }).format(date);
}

export function buildExportableProject(
  project: Project,
  roadmap: Roadmap | undefined,
  ownedProject: {
    id: string;
    title: string;
    description: string | null;
    status: string;
    progress: number;
    tags: string[];
    createdAt: Date | string;
    updatedAt: Date | string;
  },
): ExportableProject {
  const relatedLinks = [
    project.githubUrl ? { label: 'GitHub repository', url: project.githubUrl } : null,
    project.liveUrl ? { label: 'Live project', url: project.liveUrl } : null,
  ].filter((link): link is { label: string; url: string } => Boolean(link));

  return {
    id: ownedProject.id,
    title: ownedProject.title || project.title,
    description: ownedProject.description || project.description,
    status: ownedProject.status || project.status || 'Planned',
    progress: Number.isFinite(ownedProject.progress) ? ownedProject.progress : project.progress || 0,
    createdAt: new Date(ownedProject.createdAt).toISOString(),
    updatedAt: new Date(ownedProject.updatedAt).toISOString(),
    technologies: project.technologies || [],
    tags: ownedProject.tags || project.technologies || [],
    milestones: (roadmap?.steps || []).map((step) => ({
      title: step.title,
      description: step.description,
      duration: step.duration,
      completed: step.completed,
      tasks: step.tasks || [],
    })),
    relatedLinks,
  };
}

export function serializeProjectMarkdown(project: ExportableProject): string {
  const technologies = project.technologies.length
    ? project.technologies.map((item) => `\`${escapeMarkdown(item)}\``).join(', ')
    : 'Not provided';

  const tags = project.tags.length
    ? project.tags.map((item) => `\`${escapeMarkdown(item)}\``).join(', ')
    : 'Not provided';

  const milestones = project.milestones.length
    ? project.milestones
        .map((milestone, index) => {
          const tasks = milestone.tasks.length
            ? milestone.tasks
                .map((task) => `   - [ ] ${escapeMarkdown(task)}`)
                .join('\n')
            : '   - No tasks provided';

          return [
            `### ${index + 1}. ${escapeMarkdown(milestone.title)}`,
            '',
            `- **Status:** ${milestone.completed ? 'Completed' : 'Pending'}`,
            `- **Duration:** ${escapeMarkdown(milestone.duration || 'Not provided')}`,
            `- **Description:** ${escapeMarkdown(normalizeText(milestone.description))}`,
            '- **Tasks:**',
            tasks,
          ].join('\n');
        })
        .join('\n\n')
    : 'No milestones or tasks have been added yet.';

  const links = project.relatedLinks.length
    ? project.relatedLinks
        .map((link) => `- [${escapeMarkdown(link.label)}](${link.url.replace(/\)/g, '%29')})`)
        .join('\n')
    : 'No related links have been added.';

  return `# ${escapeMarkdown(project.title)}

${escapeMarkdown(normalizeText(project.description))}

## Project Summary

| Field | Value |
| --- | --- |
| Status | ${escapeMarkdown(project.status)} |
| Progress | ${Math.max(0, Math.min(100, project.progress))}% |
| Created | ${escapeMarkdown(formatDate(project.createdAt))} |
| Last updated | ${escapeMarkdown(formatDate(project.updatedAt))} |

## Technologies

${technologies}

## Tags

${tags}

## Milestones and Tasks

${milestones}

## Related Links

${links}

---

_Generated by ProjectPilot AI._
`;
}

export function serializeProjectJson(project: ExportableProject): string {
  return JSON.stringify(
    {
      ...project,
      description: normalizeText(project.description),
      progress: Math.max(0, Math.min(100, project.progress)),
      generatedAt: new Date().toISOString(),
      generatedBy: 'ProjectPilot AI',
    },
    null,
    2,
  );
}

export function downloadTextFile(content: string, fileName: string, mimeType: string): void {
  if (typeof window === 'undefined') {
    throw new Error('File downloads are only available in the browser.');
  }

  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const objectUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');

  link.href = objectUrl;
  link.download = fileName;
  link.style.display = 'none';
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(objectUrl), 0);
}
